export const PORTFOLIO_PLACEHOLDERS: Readonly<Record<string, string>> = {
  '/portfolio/projects/good-invoice/editor-and-preview.webp':
    'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAgCdASogABQAP0WYwVqwKialqAgCACiJaQAAPaOgAP7uWw7WvauErYAAAA==',
  '/portfolio/projects/good-invoice/responsive-editor.webp':
    'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABwAwCdASoZACAAP0WaxFqwKycwqAgCECiJaQAAPZgHP35YQAAA/u4p7sOVPIyNdnA5gcIA',
  '/portfolio/projects/good-invoice/display-controls-dark.webp':
    'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAwCdASoXACAAP0WYwlswKiakKAgCACiJaQDFyBanFAAA/u2J3pJn9BOdKSLo6LcAAA==',
  '/portfolio/projects/lumen/workspace-home.webp':
    'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASogABAAP0WMvFS1qaYjMAgCsCiJaQAAetHW8uEAAP7t4n0u+QuPkclO7IiYQDwAAAA=',
  '/portfolio/projects/lumen/mobile-library.webp':
    'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAwCdASoOACAAP0WKu1SwKSYjMAgCACiJaQAAewCGIIAAAP7t0WESO+QEpTrFfMi2VAAA',
  '/portfolio/projects/lumen/theme-customizer.webp':
    'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASogABAAP0WKu1SwKSYjMAgCACiJZwDCgGle2S6q/HZLaAAA/vdWXZc7SfWmmX3s/KbZM1rIUdN1n83E8X4i07jCwuIQAAAA',
  '/portfolio/projects/lumen/light-conversation.webp':
    'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABQAwCdASogABAAP0WKu1SwKSYjMAgCACiJaQAAXfCF+NC4AAD+w3arYgdfygNpfpxRT9NbJQAAAA==',
  '/portfolio/projects/calm-ai-studio/hero.webp':
    'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAwCdASogABIAP0WIvVSwKKajMBgMAgAoiWkAADpwMufqGYzbzMAA/uzqQAM/EwuQ6KJPj3dzemzOQgAAAA==',
  '/portfolio/projects/bitsnpixels/studio-hero-poster.webp':
    'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASogABAAP0WKvFSwKSYjMAgCACiJYwDLLCHe/eqEn450m0j4APw27BkvnwR3tEnsesBejnrOvOsxnvKPFsCuC6c2+QOgzhlfLv//d1NIxZzzU/2Md6tM3JE5dFkOuNeGxyDo+KAnm83/Ks/erpogIF8V1gQdCQAA',
  '/portfolio/projects/bitsnpixels/work-carousel-poster.webp':
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASogABAAP0WKvVSwKSajMAgCACiJaQABHuplbtYs/BqGM4QAAP5P9i13PNtD6OY5dYVx6sQrNNfy/oRuPmxe3XOE6I1/lZ/IEm62mEclz1DQun5s66/70Jj46xIHB2OtsVXdQ+rgAAA=',
  '/portfolio/projects/bitsnpixels/case-study-focus-poster.webp':
    'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASogAA8AP0WKu1SwKSYjMAgCACiJaQABHumJzGExOvyb7sAA/D+uSstI9CI0hSGYp4FL2nCI+uQm4vZ6Iv9VaDFxr7/kI7/fT/maEKmTubwiNFycPLNGyKZOg3Z15AKoILfV9OST1F3Sli8tgAA=',
  '/portfolio/projects/glazed/studio-overview.webp':
    'data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASogABAAP0WKu1SwKSYjMAgCACiJZQABHuqZeAlPooAA/vjPBGqAIAsBrvZ1p7ZU3Ksdz7FgCb4YprmjIZ6cMnR+Jmds9symNQAAAA==',
  '/portfolio/projects/glazed/studio-scroll-poster.webp':
    'data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASogAA8AP0WOwFWwKacjMAgCACiJaQABHuuCcDSwxkI1gAD8P5MUHqpZrgfv/txACem0d/Zqa+pUeKFzD7Say7x6wKz68xAe2nAAAA==',
  '/portfolio/projects/glazed/collaboration-cta-poster.webp':
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwBACdASogABMAPzmKuFSvKiWjMAwB4CcJaQAAW+kHT4BGgYe7q2+1I1Ac4AD8NuwZLueAgp2OrjQB1q+rp48HQXxytryrcu/WA45xaRIZkNmSZBJ+8EAA',
  '/portfolio/projects/glazed/mobile-case-study-poster.webp':
    'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoTACAAPzF6tVSupyUjN/qoAdAmCWkAAFue6USK+Bd6EzJFgbrEyAD8IsjizDGlVwzfDaXQr9OS+/+jfvtTyGr21+BhZJx/vzFl5vQQFbf2HaWMEpUsvMOfLo9lFHNPey+Pe+w/T6ki7ZSRqLuRYFTJgAA=',
  '/portfolio/projects/glazed/pricing-scroll-poster.webp':
    'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAwCdASogABAAP0WSwFSwKycjMAgCACiJaQABHun8zuLuuuAA/k/2LC7wSFtFXcU7r/zyccOGSlevBp8t9jF7j5bTu4gpx/iTsToVnc0tgAAA',
  '/portfolio/projects/folders/workspace-library.webp':
    'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBQCdASogABgAP0WMvlcwKKYjsBgIAgAoiWUAyFwREHyTKjqiLygVkfnyEy/mPa2wfEAA/sx5l7a+XIalMIrVIHdqFlnq/8CPLcxcpt2+EhTtIPXxeU2F9Pvv3DW/UfwQtQNXYGzIE+KDShWpvGu7AQGdGX6Uvkz++0a7PYktThg5EEAAAA==',
  '/portfolio/projects/folders/folder-organization-poster.webp':
    'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASogABMAP0WIuFSwKKUjMAgCACiJZQAAW7Q3xt+/1YFAAP7i4Et2Z+kkMsh81Krki0ReqKeO2HBLzu3nxyRT9vQAAAA=',
  '/portfolio/projects/orgo/overview.webp':
    'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASogABAAP0WOvFSwKiYjMAgCACiJZQAAW+1J44zBdPgZOfoAAP7jlIoarlpj0lFl/WgaTlredOp3R5WqLZnOefRg8Ibx+kc8fqhcAcHqRgAAAA==',
  '/portfolio/projects/orgo/integrations.webp':
    'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABQAwCdASogABAAP0WKu1SwKaYjMAgCACiJaQAAW+1XoeTgAAD+45R/XPUtMzpUGM4xjPjxVsyAAA==',
  '/portfolio/projects/orgo/pricing.webp':
    'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASogABMAPzmGt1SvKSUjMAwB4CcJZQAA8HUDetsY925oAP70I7nXqHoMcirL18KaIxtBxPeuD+iZSIZV5ojWgAAA',
  '/portfolio/projects/orgo/benefits.webp':
    'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwBACdASogABYAP0WMwFewKKajsBgIAgAoiWkAAC51WU7V9yh1sZhLjKZbADgAbJAA/ucYE2ISHSRcfDzMhz+fy+quHW1CStZRXm34cAHi8fvouzJDGmw38MbA8MF8dIxcvdShVm+EBbzA7mx1HF2jiVyw3dn0LBITSbATYAA=',
  '/portfolio/projects/stepper/system-states.webp':
    'data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBQCdASogABQAP0WOvVSwKiajMAgCACiJaQAAW8OtK2p9JwDcH2ZfUaz4bv4cmNXswAAA/ucf+QYj2HerVA7pQlWahw/qqj7BAM14qs+WEnZUxdpIImh49750ZNdaSMR10EwwPsRuPKWDqUCa/fUyd6Wr3+0O07P0jHmZpmtRkqw9OL+WI8/qGO6giZARZzfD0LVamOUVbgWOeycuE6RafxI/NIGYuDQHAAAA',
  '/portfolio/projects/stepper/configuration-panel.webp':
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoOACAAP0WMvlUwKSajMAgCACiJaQABHuv/qF8diqzKoAD+7SGAADtoPuOHLmMXT/Qgsb2H+T/vKpzvBMO08IY9RZ7ZVxxJ+8qV9CqkAr3Cb4TDaRaCac5AfMAAAA==',
  '/portfolio/projects/stepper/interactive-sequence-poster.webp':
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAwCdASogAA4AP0VizGAwI6qmmAIAKIlpAAEd0a61ljpcD8AA/cfPp6a7G4V8Ti0Krt+4T0YpiQ9NfdLzBl6cY81S0hHXQ0+z96oP2ddJATVLeDrKEe7HpQZ4xhZ7lVxzXu+tfL9h89AAAAA=',
  '/portfolio/projects/stepper/arrow-state-poster.webp':
    'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBQCdASoZACAAPzmItVSvKSSjMAwB4CcJYwAA8HZL13MtglaNv/nrqgyzW/uMIP9cLgAA/k+DqMQWXZHoQLzx/DyEd8vdPHPy/qJE2lrZ4Y7YGDbp4QCwUoKl/jZnzUB/15cnNGKEZ/Un6Gi7tYZVCirXTcbmTiH8tJu3mQq7Cphdik+8AAAA',
}
